package com.company.iendo.green.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.company.iendo.green.db.DeviceDBBean;
import com.company.iendo.green.db.TaskDBBean;
import com.company.iendo.green.db.UserDBBean;
import com.company.iendo.green.db.downcase.CaseDBBean;
import com.company.iendo.green.db.downcase.dwonmsg.DownVideoMessage;

import com.company.iendo.green.db.DeviceDBBeanDao;
import com.company.iendo.green.db.TaskDBBeanDao;
import com.company.iendo.green.db.UserDBBeanDao;
import com.company.iendo.green.db.CaseDBBeanDao;
import com.company.iendo.green.db.DownVideoMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceDBBeanDaoConfig;
    private final DaoConfig taskDBBeanDaoConfig;
    private final DaoConfig userDBBeanDaoConfig;
    private final DaoConfig caseDBBeanDaoConfig;
    private final DaoConfig downVideoMessageDaoConfig;

    private final DeviceDBBeanDao deviceDBBeanDao;
    private final TaskDBBeanDao taskDBBeanDao;
    private final UserDBBeanDao userDBBeanDao;
    private final CaseDBBeanDao caseDBBeanDao;
    private final DownVideoMessageDao downVideoMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceDBBeanDaoConfig = daoConfigMap.get(DeviceDBBeanDao.class).clone();
        deviceDBBeanDaoConfig.initIdentityScope(type);

        taskDBBeanDaoConfig = daoConfigMap.get(TaskDBBeanDao.class).clone();
        taskDBBeanDaoConfig.initIdentityScope(type);

        userDBBeanDaoConfig = daoConfigMap.get(UserDBBeanDao.class).clone();
        userDBBeanDaoConfig.initIdentityScope(type);

        caseDBBeanDaoConfig = daoConfigMap.get(CaseDBBeanDao.class).clone();
        caseDBBeanDaoConfig.initIdentityScope(type);

        downVideoMessageDaoConfig = daoConfigMap.get(DownVideoMessageDao.class).clone();
        downVideoMessageDaoConfig.initIdentityScope(type);

        deviceDBBeanDao = new DeviceDBBeanDao(deviceDBBeanDaoConfig, this);
        taskDBBeanDao = new TaskDBBeanDao(taskDBBeanDaoConfig, this);
        userDBBeanDao = new UserDBBeanDao(userDBBeanDaoConfig, this);
        caseDBBeanDao = new CaseDBBeanDao(caseDBBeanDaoConfig, this);
        downVideoMessageDao = new DownVideoMessageDao(downVideoMessageDaoConfig, this);

        registerDao(DeviceDBBean.class, deviceDBBeanDao);
        registerDao(TaskDBBean.class, taskDBBeanDao);
        registerDao(UserDBBean.class, userDBBeanDao);
        registerDao(CaseDBBean.class, caseDBBeanDao);
        registerDao(DownVideoMessage.class, downVideoMessageDao);
    }
    
    public void clear() {
        deviceDBBeanDaoConfig.clearIdentityScope();
        taskDBBeanDaoConfig.clearIdentityScope();
        userDBBeanDaoConfig.clearIdentityScope();
        caseDBBeanDaoConfig.clearIdentityScope();
        downVideoMessageDaoConfig.clearIdentityScope();
    }

    public DeviceDBBeanDao getDeviceDBBeanDao() {
        return deviceDBBeanDao;
    }

    public TaskDBBeanDao getTaskDBBeanDao() {
        return taskDBBeanDao;
    }

    public UserDBBeanDao getUserDBBeanDao() {
        return userDBBeanDao;
    }

    public CaseDBBeanDao getCaseDBBeanDao() {
        return caseDBBeanDao;
    }

    public DownVideoMessageDao getDownVideoMessageDao() {
        return downVideoMessageDao;
    }

}
