package com.company.iendo.green.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.company.iendo.green.db.UserDBBean;

import com.company.iendo.green.db.UserDBBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDBBeanDaoConfig;

    private final UserDBBeanDao userDBBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDBBeanDaoConfig = daoConfigMap.get(UserDBBeanDao.class).clone();
        userDBBeanDaoConfig.initIdentityScope(type);

        userDBBeanDao = new UserDBBeanDao(userDBBeanDaoConfig, this);

        registerDao(UserDBBean.class, userDBBeanDao);
    }
    
    public void clear() {
        userDBBeanDaoConfig.clearIdentityScope();
    }

    public UserDBBeanDao getUserDBBeanDao() {
        return userDBBeanDao;
    }

}
