package com.company.iendo.green.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_DBBEAN".
*/
public class UserDBBeanDao extends AbstractDao<UserDBBean, Long> {

    public static final String TABLENAME = "USER_DBBEAN";

    /**
     * Properties of entity UserDBBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DeviceID = new Property(1, String.class, "deviceID", false, "DEVICE_ID");
        public final static Property Ip = new Property(2, String.class, "ip", false, "IP");
        public final static Property HttpPort = new Property(3, String.class, "httpPort", false, "HTTP_PORT");
        public final static Property SocketPort = new Property(4, String.class, "socketPort", false, "SOCKET_PORT");
        public final static Property LivePort = new Property(5, String.class, "livePort", false, "LIVE_PORT");
        public final static Property MicPort = new Property(6, String.class, "micPort", false, "MIC_PORT");
        public final static Property Username = new Property(7, String.class, "username", false, "USERNAME");
        public final static Property Password = new Property(8, String.class, "password", false, "PASSWORD");
        public final static Property Title = new Property(9, String.class, "title", false, "TITLE");
        public final static Property Msg = new Property(10, String.class, "msg", false, "MSG");
        public final static Property Type = new Property(11, String.class, "type", false, "TYPE");
        public final static Property EndoType = new Property(12, String.class, "endoType", false, "ENDO_TYPE");
    }


    public UserDBBeanDao(DaoConfig config) {
        super(config);
    }
    
    public UserDBBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_DBBEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DEVICE_ID\" TEXT UNIQUE ," + // 1: deviceID
                "\"IP\" TEXT," + // 2: ip
                "\"HTTP_PORT\" TEXT," + // 3: httpPort
                "\"SOCKET_PORT\" TEXT," + // 4: socketPort
                "\"LIVE_PORT\" TEXT," + // 5: livePort
                "\"MIC_PORT\" TEXT," + // 6: micPort
                "\"USERNAME\" TEXT," + // 7: username
                "\"PASSWORD\" TEXT," + // 8: password
                "\"TITLE\" TEXT," + // 9: title
                "\"MSG\" TEXT," + // 10: msg
                "\"TYPE\" TEXT," + // 11: type
                "\"ENDO_TYPE\" TEXT);"); // 12: endoType
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_DBBEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserDBBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deviceID = entity.getDeviceID();
        if (deviceID != null) {
            stmt.bindString(2, deviceID);
        }
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(3, ip);
        }
 
        String httpPort = entity.getHttpPort();
        if (httpPort != null) {
            stmt.bindString(4, httpPort);
        }
 
        String socketPort = entity.getSocketPort();
        if (socketPort != null) {
            stmt.bindString(5, socketPort);
        }
 
        String livePort = entity.getLivePort();
        if (livePort != null) {
            stmt.bindString(6, livePort);
        }
 
        String micPort = entity.getMicPort();
        if (micPort != null) {
            stmt.bindString(7, micPort);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(8, username);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(9, password);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(10, title);
        }
 
        String msg = entity.getMsg();
        if (msg != null) {
            stmt.bindString(11, msg);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(12, type);
        }
 
        String endoType = entity.getEndoType();
        if (endoType != null) {
            stmt.bindString(13, endoType);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserDBBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String deviceID = entity.getDeviceID();
        if (deviceID != null) {
            stmt.bindString(2, deviceID);
        }
 
        String ip = entity.getIp();
        if (ip != null) {
            stmt.bindString(3, ip);
        }
 
        String httpPort = entity.getHttpPort();
        if (httpPort != null) {
            stmt.bindString(4, httpPort);
        }
 
        String socketPort = entity.getSocketPort();
        if (socketPort != null) {
            stmt.bindString(5, socketPort);
        }
 
        String livePort = entity.getLivePort();
        if (livePort != null) {
            stmt.bindString(6, livePort);
        }
 
        String micPort = entity.getMicPort();
        if (micPort != null) {
            stmt.bindString(7, micPort);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(8, username);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(9, password);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(10, title);
        }
 
        String msg = entity.getMsg();
        if (msg != null) {
            stmt.bindString(11, msg);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(12, type);
        }
 
        String endoType = entity.getEndoType();
        if (endoType != null) {
            stmt.bindString(13, endoType);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserDBBean readEntity(Cursor cursor, int offset) {
        UserDBBean entity = new UserDBBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // deviceID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ip
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // httpPort
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // socketPort
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // livePort
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // micPort
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // username
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // password
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // title
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // msg
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // type
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // endoType
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserDBBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIp(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHttpPort(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSocketPort(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLivePort(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setMicPort(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUsername(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPassword(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTitle(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMsg(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setType(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setEndoType(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserDBBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserDBBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserDBBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
